### ISSUE TITLE
Can the xodus-queue be configured?

### ISSUE THREAD

**Issue by marchuss** [ralscha/xodus-queue#1]
I've been experimenting with the xodus-queue and really like the way it is light-weight and uses the same interface as Java Queue.

One question I had was if a large number of items are sent to the queue then I can see that files are persisted to disk containing the queue items and on restart, the application correctly processes the persisted items.  However, if only a small number of items are sent to the queue, they are correctly persisted to disk and I can see the items in the persisted queue, but for some reason they are not reread when the service is restarted if I interrupt the processing of the queue.

Is this due to some configuration option that needs to be set (was trying to understand why this works correctly for large batches and not smaller ones)?

Thanks

**Comment by ralscha** [comment]
Looks like there might be a bug somewhere. Can you quantify "large" and "small" number of items. Maybe I'm able to reproduce the problem.

**Comment by ralscha** [comment]
Another thing you can try is referencing the latest Xodus library. Version 1.0.1 of my library references an older version. Add this to your pom.xml 

```
  <dependency>
    <groupId>org.jetbrains.xodus</groupId>
    <artifactId>xodus-environment</artifactId>
    <version>1.3.124</version>
  </dependency>
```

**Comment by marchuss** [comment]
Thank you, I'll try this out.  The large batch contained 160,000 items and the small batch contained just 14 items.  First thing to try will be for me to update the library version

**Comment by marchuss** [comment]
If I add this dependency:
<dependency>
    <groupId>org.jetbrains.xodus</groupId>
    <artifactId>xodus-environment</artifactId>
    <version>1.3.124</version>
  </dependency>

along with the existing xodus-queue dependency it seems to have fixed the issue.  Thank you

**Comment by ralscha** [comment]
Interesting. I'd better release a 1.0.2 version that references the latest Xodus library.

**Comment by ralscha** [comment]
Version 1.0.2 released. Should appear in the central maven repository in a few hours. 
Only changes are the updated dependencies.

By the way you can configure the underlying Xodus database with this constructor
```
public XodusQueue(final LogConfig logConfig,
			final EnvironmentConfig environmentConfig,
			final XodusQueueSerializer<T> serializer) {
```

**Comment by marchuss** [comment]
Using the updated dependency has fixed the problem and regardless of the batch size the service survives a restart
